### ISSUE TITLE
'Could not find a primary key for PlayListTrack' when importing using MySql

### ISSUE THREAD

**Issue by casertap** [neo4jrb/neo4apis#7]
Following this blog post: http://neo4j.com/blog/loading-sql-neo4j-like-magic/
with the difference of using the Chinook_Mysql.sql database
and importing into a mysql database using utf8 encoding.

I get a stack saying: Could not find a primary key for PlayListTrack

<img width="1440" alt="screen shot 2015-08-26 at 10 29 14" src="https://cloud.githubusercontent.com/assets/284394/9495373/891bb404-4c0b-11e5-9f18-59fa5087b73a.png">

**Comment by casertap** [comment]
I decided to give it another try because I really wanted to play with the awesome neo4j graph visualization tool. 
So I installed postgres on my vm machine and tried again to import the database.
It fails the same way.

<img width="1440" alt="screen shot 2015-08-28 at 13 06 36" src="https://cloud.githubusercontent.com/assets/284394/9545020/094d153e-4d86-11e5-8233-a6cf931c713a.png">

**Comment by cheerfulstoic** [comment]
I'll have a look at this now

**Comment by cheerfulstoic** [comment]
Ok, I've just updated `neo4apis-activerecord` to 0.9.0 which should now support this (tables with just two integers will be assumed to be a many-to-many table and will be created as a relationship).  I also updated `neo4apis` by a patch version, so be on the lookout for that.

If you're using something other than the default username/password/port then you can use the `--neo4j-url` option like so:

```
neo4apis activerecord all_tables --neo4j-url "http://username:password@localhost:7000" --identify-model --import-all-associations --debug
```

Let me know how that works.

I'm thinking I should build a stripped down version of the Chinook database and have tests which automatically load it into different databases and then test the end result in Neo4j after running it through `neo4apis-activerecord`.

One reason is that I'd like to improve the solution that I made.  Rather than looking for just a table with two integers, it should find if there are two columns which are foreign keys to another table because there might be other associated data.  Tests should help build this sort of complexity out in a sane manner.

**Comment by casertap** [comment]
Ok I am trying this: you require pry somewhere and I got a require problem with this
```
include_list
[:customer]
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- pry (LoadError)
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/activerecord.rb:53:in `add_model_relationship'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/activerecord.rb:35:in `block (2 levels) in model_importer'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/activerecord.rb:30:in `each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/activerecord.rb:30:in `block in model_importer'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-0.8.2/lib/neo4apis/base.rb:62:in `instance_exec'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-0.8.2/lib/neo4apis/base.rb:62:in `import'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/cli/activerecord.rb:83:in `block (3 levels) in import_models_or_tables'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/batches.rb:51:in `each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/batches.rb:51:in `block in find_each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/batches.rb:124:in `find_in_batches'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/batches.rb:50:in `find_each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/cli/activerecord.rb:82:in `block (2 levels) in import_models_or_tables'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/cli/activerecord.rb:75:in `each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/cli/activerecord.rb:75:in `block in import_models_or_tables'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-0.8.2/lib/neo4apis/base.rb:54:in `batch'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/cli/activerecord.rb:74:in `import_models_or_tables'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/cli/activerecord.rb:45:in `all_tables'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-0.8.2/bin/neo4apis:15:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/neo4apis:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/neo4apis:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
````

I added it to my Gemfile now I have 
````
vagrant@packer-virtualbox-iso-1411922062:/vagrant/chinook$ neo4apis activerecord all_tables --neo4j-url "http://127.0.0.1:7000" --identify-model --import-all-associations --debug
requiring neo4apis-activerecord
Defining: belongs_to :customer, foreign_key: "CustomerId", class_name: "Customer"
Defining: belongs_to :playlist, foreign_key: "PlaylistId", class_name: "Playlist"
Defining: belongs_to :track, foreign_key: "TrackId", class_name: "Track"
Defining: belongs_to :artist, foreign_key: "ArtistId", class_name: "Artist"
WARNING: Could not find a table for SupportRep.
Defining: belongs_to :invoice, foreign_key: "InvoiceId", class_name: "Invoice"
Defining: belongs_to :track, foreign_key: "TrackId", class_name: "Track"
Defining: belongs_to :album, foreign_key: "AlbumId", class_name: "Album"
Defining: belongs_to :media_type, foreign_key: "MediaTypeId", class_name: "MediaType"
Defining: belongs_to :genre, foreign_key: "GenreId", class_name: "Genre"
Importing tables: Genre, Invoice, Artist, PlaylistTrack, Employee, Album, Customer, InvoiceLine, Playlist, MediaType, Track
include_list
[]
include_list
[:customer]
include_list
[]
include_list
[:playlist, :track]
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `async_exec': PG::UndefinedColumn: ERROR:  column PlaylistTrack.playlistid does not exist (ActiveRecord::StatementInvalid)
LINE 1: ...0) AND ("PlaylistTrack"."TrackId" >= 0)  ORDER BY "PlaylistT...
                                                             ^
: SELECT  "PlaylistTrack".* FROM "PlaylistTrack" WHERE ("PlaylistTrack"."PlaylistId" >= 0) AND ("PlaylistTrack"."TrackId" >= 0)  ORDER BY "PlaylistTrack".PlaylistId ASC,"PlaylistTrack".TrackId ASC LIMIT 1000
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `block in exec_no_cache'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `exec_no_cache'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:588:in `execute_and_clear'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:351:in `select'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/querying.rb:39:in `find_by_sql'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation.rb:638:in `exec_queries'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation.rb:514:in `load'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation.rb:243:in `to_a'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:509:in `find_last'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:160:in `last'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/composite_primary_keys-8.1.1/lib/composite_primary_keys/relation/batches.rb:31:in `find_in_batches'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/batches.rb:50:in `find_each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/cli/activerecord.rb:82:in `block (2 levels) in import_models_or_tables'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/cli/activerecord.rb:75:in `each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/cli/activerecord.rb:75:in `block in import_models_or_tables'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-0.8.2/lib/neo4apis/base.rb:54:in `batch'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/cli/activerecord.rb:74:in `import_models_or_tables'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-activerecord-0.9.0/lib/neo4apis/cli/activerecord.rb:45:in `all_tables'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4apis-0.8.2/bin/neo4apis:15:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/neo4apis:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/neo4apis:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
````

**Comment by casertap** [comment]
With Mysql it worked!

**Comment by cheerfulstoic** [comment]
D'oh regarding postgres, but yay regarding mySQL!

I released a 0.9.1 without the pry call (d'oh again...).

I might try putting together a test suite for this this evening and getting it running on Travis CI (even if the code isn't working perfectly, baby steps...)

Thanks!

**Comment by cheerfulstoic** [comment]
Actually, going to re-open because of the PG issue

**Comment by casertap** [comment]
Ok nice good for the mysql part. It was enough to have the db up and running.
Now I will be able to try all re request you show on your screencast.
Keep up the good work.
